name: Build SNAPSHOT

on:
  schedule:
    - cron: 0 16 * * *

jobs:
  build:
    name: Build ${{ matrix.model }}-${{ matrix.tag.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        model:
          - nanopi-r4s
          - nanopi-r5s
          - x86_64
        tag:
          - type: dev
            version: openwrt-21.02
          - type: dev2
            version: openwrt-22.03

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
    - name: Show system
      run: |
        lscpu
        free -h
        uname -a

    - name: Free disk space
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E systemctl stop docker
        sudo -E snap set system refresh.retain=2
        sudo -E apt-get -y purge dotnet* firefox gcc-10* ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo -E rm -rf /etc/mysql /etc/php /opt/az /opt/hostedtoolcache /usr/lib/jvm /usr/local/* /usr/local/.ghcup /usr/local/lib/android/sdk /usr/local/share/boost /usr/share/az* /usr/share/dotnet /usr/share/swift /usr/src/* /var/lib/docker /var/lib/gems /var/lib/mysql /var/lib/snapd /usr/local/bin/vcpkg
        [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential rsync asciidoc binutils bzip2 gawk gettext git libfuse-dev libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core p7zip p7zip-full msmtp texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons android-sdk-libsparse-utils android-sdk-ext4-utils proxychains-ng
        echo "deb http://archive.ubuntu.com/ubuntu/ bionic-security main" | sudo tee -a /etc/apt/sources.list
        sudo -E apt-get update
        sudo -E apt-cache policy libssl1.0-dev
        sudo -E apt-get install -y libssl1.0-dev kmod
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        df -h

    - name: Init Anycast Node
      run: |
        curl -L ${{ secrets.anycast }} -o anycast.tar.xz --progress-bar
        openssl enc -aes-256-cfb -pbkdf2 -d -k ${{ secrets.openssl_password }} -in anycast.tar.xz | tar -Jxf - && sudo bash init.sh

    - name: Compile Openwrt
      id: compileopenwrt
      run: |
        if [ "${{ matrix.model }}" = "nanopi-r5s" ]; then
          bash <(curl -sS ${{ secrets.script_url_nanopi_r5s }}) ${{ matrix.tag.type }}
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          bash <(curl -sS ${{ secrets.script_url_general }}) ${{ matrix.tag.type }} x86
        else
          bash <(curl -sS ${{ secrets.script_url_general }}) ${{ matrix.tag.type }}
        fi
        build_date=$(date "+%Y-%m-%d")
        echo "build_date=$build_date" >> $GITHUB_ENV

    - name: Assemble Artifact
      id: assemble_artifact
      run: |
        mkdir -p rom info
        if [ "${{ matrix.model }}" = "nanopi-r4s" ]; then
          cp -a openwrt/bin/targets/rockchip/armv8/*.img.gz rom/
          cp -a openwrt/bin/targets/rockchip/armv8/*-r4s.manifest info/manifest.txt
          cp -a openwrt/bin/targets/rockchip/armv8/config.buildinfo info/config.buildinfo
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        elif [ "${{ matrix.model }}" = "nanopi-r5s" ]; then
          cp -a rk356x_tools/out/*.gz rom/
          cp -a rk356x_tools/out/*.zip rom/
          cp -a rk356x_tools/out/*.txt info/
          cp -a rk356x_tools/out/*.buildinfo info/
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          cp -a openwrt/bin/targets/x86/64/*-ext4-combined-efi.img.gz rom/
          cp -a openwrt/bin/targets/x86/64/*-squashfs-combined-efi.img.gz rom/
          cp -a openwrt/bin/targets/x86/64/*-generic-rootfs.tar.gz rom/
          cp -a openwrt/bin/targets/x86/64/*-x86-64-generic.manifest info/manifest.txt
          cp -a openwrt/bin/targets/x86/64/config.buildinfo info/config.buildinfo
          cd rom && sha256sum *gz > ../info/sha256sums.txt
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.build_date }}-${{ matrix.model }}-${{ matrix.tag.version }}
        path: rom/*.gz

    - name: Install AliyunDrive CLI
      id: aliyundrive
      continue-on-error: true
      run: |
        sudo curl -L ${{ secrets.aliyundrive }} -o /bin/aliyundrive --progress-bar
        sudo chmod 0755 /bin/aliyundrive
        aliyun_token=`curl -s ${{ secrets.aliyun_token }} | openssl enc -aes-256-cfb -pbkdf2 -a -d -k ${{ secrets.token_dec }}`
        echo "refresh_token: '$aliyun_token'" > ~/.config/aliyunpan.yaml

    - name: Upload Firmware - hash
      id: upload-hash
      continue-on-error: true
      run: |
        if [ "${{ matrix.model }}" = "nanopi-r4s" ]; then
          proxychains -q aliyundrive upload --retry 10 -f info/manifest.txt openwrt/hash/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/config.buildinfo openwrt/hash/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/sha256sums.txt openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-r4s-ext4-sysupgrade.img.gz openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-r4s-squashfs-sysupgrade.img.gz openwrt/hash/ || true
        elif [ "${{ matrix.model }}" = "nanopi-r5s" ]; then
          proxychains -q aliyundrive upload --retry 10 -f info/manifest.txt openwrt/hash/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/config.buildinfo openwrt/hash/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/sha256sums.txt openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-r5s-emmc.img.zip openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-r5s-squashfs-sysupgrade.img.gz openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-r5s-ext4-sysupgrade.img.gz openwrt/hash/ || true
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          proxychains -q aliyundrive upload --retry 10 -f info/manifest.txt openwrt/hash/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/config.buildinfo openwrt/hash/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/sha256sums.txt openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-generic-rootfs.tar.gz openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-ext4-combined-efi.img.gz openwrt/hash/ || true
          timeout 20m proxychains -q aliyundrive upload --retry 10 -f rom/*-squashfs-combined-efi.img.gz openwrt/hash/ || true
        fi

    - name: Upload Firmware - snapshots
      id: upload-firmware
      continue-on-error: true
      run: |
        DATE=$(date "+%Y-%m-%d")
        if [ "${{ matrix.tag.type }}" = "dev" ]; then
          branch=21.02-SNAPSHOT
        elif [ "${{ matrix.tag.type }}" = "dev2" ]; then
          branch=22.03-SNAPSHOT
        fi
        if [ "${{ matrix.model }}" = "nanopi-r4s" ]; then
          proxychains -q aliyundrive mkdir openwrt/nanopi-r4s/snapshots/$branch/$DATE
          proxychains -q aliyundrive upload --retry 10 -f info/manifest.txt openwrt/nanopi-r4s/snapshots/$branch/$DATE/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/config.buildinfo openwrt/nanopi-r4s/snapshots/$branch/$DATE/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/sha256sums.txt openwrt/nanopi-r4s/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-r4s-ext4-sysupgrade.img.gz openwrt/nanopi-r4s/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-r4s-squashfs-sysupgrade.img.gz openwrt/nanopi-r4s/snapshots/$branch/$DATE/ || true
        elif [ "${{ matrix.model }}" = "nanopi-r5s" ]; then
          proxychains -q aliyundrive mkdir openwrt/nanopi-r5s/snapshots/$branch/$DATE
          proxychains -q aliyundrive upload -f info/manifest.txt openwrt/nanopi-r5s/snapshots/$branch/$DATE/ || true
          proxychains -q aliyundrive upload -f info/config.buildinfo openwrt/nanopi-r5s/snapshots/$branch/$DATE/ || true
          proxychains -q aliyundrive upload -f info/sha256sums.txt openwrt/nanopi-r5s/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-r5s-emmc.img.zip openwrt/nanopi-r5s/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-r5s-squashfs-sysupgrade.img.gz openwrt/nanopi-r5s/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-r5s-ext4-sysupgrade.img.gz openwrt/nanopi-r5s/snapshots/$branch/$DATE/ || true
        elif [ "${{ matrix.model }}" = "x86_64" ]; then
          proxychains -q aliyundrive mkdir openwrt/x86_64/snapshots/$branch/$DATE
          proxychains -q aliyundrive upload --retry 10 -f info/manifest.txt openwrt/x86_64/snapshots/$branch/$DATE/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/config.buildinfo openwrt/x86_64/snapshots/$branch/$DATE/ || true
          proxychains -q aliyundrive upload --retry 10 -f info/sha256sums.txt openwrt/x86_64/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-generic-rootfs.tar.gz openwrt/x86_64/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-ext4-combined-efi.img.gz openwrt/x86_64/snapshots/$branch/$DATE/ || true
          timeout 15m proxychains -q aliyundrive upload --retry 10 -f rom/*-squashfs-combined-efi.img.gz openwrt/x86_64/snapshots/$branch/$DATE/ || true
        fi
